package throwException;

public class test {

	public static void main(String[] args) throws studentException {
		
		
			student s1= student.find("1234");
		
			
		
	}

}
